.defaults:
  only:
    - merge_requests
    - master@chaen/chrissquare-hack-a-ton

.defaults-micromamba:
  extends: .defaults
  image: registry.cern.ch/docker.io/mambaorg/micromamba
  before_script:
    - micromamba env create --file environment.yml --name test-env
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate test-env
    - pip install git+https://github.com/chaen/DIRAC.git@chris-hack-a-ton
    - pip install .

pre-commit:
  extends: .defaults
  image: registry.cern.ch/docker.io/library/python:3.11
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

pytest:
  extends: .defaults-micromamba
  script:
    - pytest . --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

mypy:
  extends: .defaults-micromamba
  script:
    - mypy .
