diracx:
  developer:
    enabled: true
  diracx:
    hostname: gubbinsdiracx.example.com
    sqlDbs:
      dbs:
        LollygagDB:
  global:
    images:
      tag: "dev"
      services: ghcr.io/diracgrid/gubbins/services
