name: Draft on Changes Requested

on:
  workflow_run:
    workflows: ["Record Changes Requested"]
    types: [completed]

permissions: {}

jobs:
  draft:
    if: github.event.workflow_run.conclusion == 'success'
    uses: DIRACGrid/management/.github/workflows/draft-on-changes-requested.yml@master
    secrets:
      token: ${{ secrets.DRAFT_PAT }}
